#ifndef UIDEFINES_H
#define UIDEFINES_H
typedef enum _UI_PTZ {
    UI_PTZ_ZOOM_FOCUS,
    UI_PTZ_ZOOM_IN,
    UI_PTZ_ZOOM_OUT,

    UI_PTZ_UP,
    UI_PTZ_DOWN,
    UI_PTZ_RIGHT,
    UI_PTZ_LEFT,
    UI_PTZ_UP_LEFT,
    UI_PTZ_UP_RIGHT,
    UI_PTZ_DOWN_LEFT,
    UI_PTZ_DOWN_RIGHT,
    UI_PTZ_STOP_ALL,

    UI_PTZ_PRE_POS_SAVE,
    UI_PTZ_PRE_POS_ROLL,
    UI_PTZ_PRE_POS_DEL,

    UI_PTZ_W_WIPER_ON,
    UI_PTZ_W_WIPER_OFF,

    UI_PTZ_LIGHT_ON,
    UI_PTZ_LIGHT_OFF,

    UI_PTZ_WARM_ON,
    UI_PTZ_WARM_OFF,

    UI_PTZ_INFRARED_ON,
    UI_PTZ_INFRARED_OFF,

    UI_PTZ_LINE_SCAN_START,
    UI_PTZ_LINE_SCAN_STOP,

    UI_PTZ_CRUISE_START,
    UI_PTZ_CRUISE_STOP,

    UI_PTZ_PRE_POS_CRUISE_START,
    UI_PTZ_PRE_POS_CRUISE_STOP,

    UI_PTZ_LOCK,
    UI_PTZ_UNLOCK,

    UI_PTZ_CMD_NONE
} UI_PTZ_CMD;

#endif // UIDEFINES_H
